version: '3.4'

services:

  redis:
    image: redis:latest
    hostname: redis

  flaskcelerypregen:
    image: flaskcelerypregen
    container_name: flaskcelerypregen
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ./scripts/run_server.sh
    volumes:
      - .:/flask-celery-pregen
    ports:
      - "5000:5000"
    links:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/run_celery.sh
    volumes:
      - .:/flask-celery-pregen
    links:
      - redis
    environment:
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/flask-celery-pregen
    command: flower -A app.resources.thumbnail_task.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5556:5555"
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - flaskcelerypregen
      - redis
      - worker